name: PR Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory ./TestResults
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/**/*.trx
        retention-days: 30
        if-no-files-found: error
        
    - name: Upload code coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: TestResults/**/coverage.cobertura.xml
        retention-days: 30
        if-no-files-found: warn
        
    - name: Publish test results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: TestResults/**/*.trx
        reporter: dotnet-trx
        fail-on-error: true
        
    - name: Code Coverage Report
      if: always()
      continue-on-error: true
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: TestResults/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'
        
    - name: Add Coverage PR Comment
      if: github.event_name == 'pull_request' && always()
      continue-on-error: true
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md
